<?php

/**
 * @var $block \Arun\FreeShippingBar\Block\FreeShippingBar
 * This phtml is responsible for the showing the bar in all pages
 * the id "block-container" will gets updated when Add to cart / Mini cart updates
 */

$isEnabled = $block->isEnabled();

?>
<?php if ($isEnabled) : ?>
        <div id="block-container">
                <?php echo __($block->getFreeShippingMessage()); ?>
        </div>
<?php endif; ?>